// <auto-generated />
namespace WebShop_Random.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initaspnetidentitytable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initaspnetidentitytable));
        
        string IMigrationMetadata.Id
        {
            get { return "202203290805016_init asp.net identity table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
